"""add price_per_corner_snapshot to work_order_step_tools

Revision ID: 64b235e5731f
Revises: 8c0f00fe6e50
Create Date: 2026-07-24 12:42:44.217126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b235e5731f'
down_revision: Union[str, None] = '8c0f00fe6e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_step_tools', sa.Column('price_per_corner_snapshot', sa.Numeric(precision=14, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_step_tools', 'price_per_corner_snapshot')
    # ### end Alembic commands ###
