"""initial schema

Revision ID: 8c0f00fe6e50
Revises: 
Create Date: 2026-07-24 11:58:17.982856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0f00fe6e50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fixed_expenses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period IN ('daily', 'monthly')", name='ck_fixed_expenses_period'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('production', 'administrative')", name='ck_personnel_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('corner_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price_per_corner', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'staff')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('machine_costs',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('hourly_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valid_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_costs',
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('days_per_month', sa.Integer(), nullable=False),
    sa.Column('hours_per_day', sa.Integer(), nullable=False),
    sa.Column('hourly_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valid_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_expenses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('unit_raw_material_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_production_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('profit_percent', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_sale_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('extra_cost', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_work_orders_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order_steps',
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('unit_process_seconds', sa.Integer(), nullable=False),
    sa.Column('machine_hourly_cost_snapshot', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('step_unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_net_price_contribution', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_productions',
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('actual_unit_seconds', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_contribution', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['work_order_steps.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order_step_personnel',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('hourly_cost_snapshot', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['work_order_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order_step_tools',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('corners_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['work_order_steps.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_production_personnel',
    sa.Column('daily_production_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_production_id'], ['daily_productions.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_production_personnel')
    op.drop_table('work_order_step_tools')
    op.drop_table('work_order_step_personnel')
    op.drop_table('daily_productions')
    op.drop_table('work_order_steps')
    op.drop_table('work_orders')
    op.drop_table('special_expenses')
    op.drop_table('personnel_costs')
    op.drop_table('machine_costs')
    op.drop_table('users')
    op.drop_table('tools')
    op.drop_table('personnel')
    op.drop_table('machines')
    op.drop_table('fixed_expenses')
    op.drop_table('customers')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
