"""add setup_seconds to work_order_steps

Revision ID: 96114ed1c3ef
Revises: 64b235e5731f
Create Date: 2026-07-26 13:15:17.624790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96114ed1c3ef'
down_revision: Union[str, None] = '64b235e5731f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_steps', sa.Column('setup_seconds', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_steps', 'setup_seconds')
    # ### end Alembic commands ###
