"""add daily_reports table

Revision ID: f8e03b88b74e
Revises: 96114ed1c3ef
Create Date: 2026-07-26 14:17:33.929102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e03b88b74e'
down_revision: Union[str, None] = '96114ed1c3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
